### ISSUE TITLE
想请教一个论文中关于感受野大小的问题

### ISSUE THREAD

**Issue by hanswzq** [XHChencs/baer_fault_diagnosis#1]
您好，最近在做毕业设计，看了您的论文感到受益匪浅！在此想问您一个问题，您文中的“We employed a large receptive field (20 × 20 and 10 × 10) for CNN_1 to automatically extract low frequency features, whereas CNN_2 extracts features from high frequency signals, hence uses a smaller receptive field (6 × 6).”这句话应该怎样理解，即为什么较大的感受野适合提取低频特征，较小的感受野适合提取高频特征？希望得到您的回复，万分感谢！

**Comment by Xiaohan-Chen** [comment]
您好，非常高兴阅读我们的论文。感受野大小是受人眼视觉启发，当我们需要关注某一个物体的局部细节的时候，视觉的感受野会聚焦在很小的一片区域，当我们需要关注一个物体的整体特征的时候，视觉所需要聚焦的区域就会很大。在一维信号中，波形都是由不同频率的基波叠加而成，它们中有高频信号，也有低频信号。低频信号的周期长，如果感受野选择太小，不够一个周期，可能CNN就不能很好的提取出低频信号中的特征；同理，高频信号周期短，如果感受野选择过大，也有可能无法提取出高频信号的特征。经过实验验证，选用不同感受野的CNN确实要比单个感受野的CNN效果更好。希望能对你有所帮助，祝你学业顺利！

**Comment by hanswzq** [comment]
非常感谢您的回答！然后再想请问您一下两个池化层的输出做点积这一步是在进行特征融合吗？谢谢！

**Comment by hanswzq** [comment]
非常感谢您的回答！然后再想请问您一下您两个池化层的输出做点积这一步是在进行特征融合吗？如果我不做点积而是卷积核先大后小按顺序排下去，直接到LSTM层的话的话会有什么影响吗？刚接触神经网络，有些地方不太懂，烦请不吝赐教，谢谢！

**Comment by Xiaohan-Chen** [comment]
两个卷积神经网络会得到两个输出，在输入到长短时记忆之前需要让它“合二为一”，可以选择的办法有拼接和融合，这里我选择了融合，即做点积。“如果我不做点积而是卷积核先大后小按顺序排下去，直接到LSTM层的话的话会有什么影响吗？”我没太明白这句话的意思，如果一直做卷积运算，最后会得到一个M*N矩阵（M是channel，N是每个channel里特征的个数，且M远远大于N）。当然长短时记忆网络只是我选择的一个特征提取器，你还可以将它换成其它的。

**Comment by hanswzq** [comment]
非常感谢您的回复！昨天因为有些事没及时回复实在抱歉。因为我在哈工大张伟硕士的论文https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD201801&filename=1017864225.nh&v=RgV4Ba4oUBzws3qiEFm%25mmd2FME9pkj8ipka60TDiuFwkAFROyzxe068pWnRfyOouy5LV
中看到他提出的wdcnn模型是 卷积层（大卷积核64*1）-池化-卷积层（小卷积核3*1）-池化-...（若干卷积层（小卷积核3*1）-池化）...-全连接层-softmax层，所以我把这个模型跟您提出的模型有些混淆了，我在想他的模型是您所说的“拼接”？还是只是单独的一个CNN模型。再次感谢您的耐心解答，也祝您学业顺利！

**Comment by hanswzq** [comment]
非常感谢您的回复！昨天因为有些事没及时回复实在抱歉。因为我在哈工大张伟硕士的论文https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD201801&filename=1017864225.nh&v=RgV4Ba4oUBzws3qiEFm%25mmd2FME9pkj8ipka60TDiuFwkAFROyzxe068pWnRfyOouy5LV
中看到他提出的wdcnn模型是 卷积层（大卷积核64*1）-池化-卷积层（小卷积核3*1）-池化-...（若干卷积层（小卷积核3*1）-池化）...-全连接层-softmax层，所以我把这个模型跟您提出的模型有些混淆了，我在想他的模型是您所说的“拼接”？还是只是单独的一个CNN模型。再次感谢您的耐心解答，也祝您学业顺利！

**Comment by hanswzq** [comment]
非常感谢您的回复！昨天因为有些事没及时回复实在抱歉。因为我在哈工大张伟硕士的论文https://kns.cnki.net/kcms/detail/detail.aspx?dbcode=CMFD&dbname=CMFD201801&filename=1017864225.nh&v=RgV4Ba4oUBzws3qiEFm%25mmd2FME9pkj8ipka60TDiuFwkAFROyzxe068pWnRfyOouy5LV
中看到他提出的wdcnn模型是 卷积层（大卷积核64x1）-池化-卷积层（小卷积核3x1）-池化-...（若干卷积层（小卷积核3x1）-池化）...-全连接层-softmax层，所以我把这个模型跟您提出的模型有些混淆了，我在想他的模型是您所说的“拼接”？还是只是单独的一个CNN模型。再次感谢您的耐心解答，也祝您学业顺利！

**Comment by Xiaohan-Chen** [comment]
您好，我目前没法登录知网所以不知道这篇论文的具体内容，但从你的描述来看应该不是拼接。我这里所说的拼接和numpy中的hstack函数类似，具体请参考[https://numpy.org/doc/stable/reference/generated/numpy.hstack.html?highlight=hstack#numpy.hstack](url)。拼接的目的是为了把两个特征（即两个矩阵）合成一个特征组（即一个矩阵），方便后面的运算。

**Comment by hanswzq** [comment]
嗯嗯学习了，非常感谢您！

**Comment by Xiaohan-Chen** [comment]
客气了，祝学业顺利！
