### ISSUE TITLE
请问关于data部分

### ISSUE THREAD

**Issue by KQiao-xp** [XHChencs/baer_fault_diagnosis#2]
您好，读完您的文章受益良多，想要运行您的代码学学经验。但是遇到一个问题，就是所需data是怎样处理的？是将相关10个文件都截取相对长度部分，然后放在data文件夹中再去运行模型代码吗？期待您的回复，感谢！

**Comment by KQiao-xp** [comment]
问题解决了，您的想法真的太棒了！还有一个疑问，请问您的那些实验结果图是如何绘画的，以及意义是什么呢？看的不是很理解

**Comment by Xiaohan-Chen** [comment]
您好，感谢您阅读我们的文章。不知道您说的是哪些图，由于其它图比较好理解我这里姑且认为指的是图9和10。它们是各层激活函数输出的图片，颜色越深表明该神经元输出值越大，反之亦然。这两幅图片主要是帮助理解在输入不同类型信号时神经元的响应结果。若想要绘制这类图片可以搜索神经元隐藏层激活函数绘制便可得到相关文章，希望对您有所帮助。

**Comment by KQiao-xp** [comment]
感谢您的耐心解答，我搜索了但是还是不太明白，并没有找到像您展示的图9：带有信号输入的隐藏层可视化 那样的绘制方法。同时，还想请教您图12：基于T-SNE的特征可视化 又是如何绘制出来的。如果允许的话，可以学习您关于绘图部分的代码吗？不胜感激。我的邮箱：（kqiaoxp@gmail.com）。最后有一点，关于我的理解，如有错误还请海涵：关于您在训练模型的时候，没有划分valid集，您是不是误把test当作valid。期待您的再一次回复！

**Comment by Xiaohan-Chen** [comment]
您好，1.可以尝试搜索可视化神经网络中间层应该找到很多解决办法，在这里我就不做相关推荐；2.T-SNE可视化方法可参考sklearn的相关[API](https://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html)，希望能帮到您；3.该demo没有提供测试环节，如若想检验模型效果可保存模型及参数在测试集上验证即可。

**Comment by KQiao-xp** [comment]
受益良多，感谢您的帮助。祝生活美满！
还想再请教您一个问题，就是刚开始对于原始数据进行下采样，会带来什么影响呢？

**Comment by Xiaohan-Chen** [comment]
您好，对原数据进行下采样主要目的是减小训练样本数量，加快训练速度。不进行下采样理论上来说不会对模型表现产生太大影响。下采样方法参考了一篇文献，在那篇文献中，采用下采样之后模型也同样取得了不错的结果同时训练速度也得到了提升。但由于文献管理混乱那篇文献目前没能找到，不过代码中的下采样方法和参数与那篇文献保持一致，希望能对你有所帮助。

**Comment by KQiao-xp** [comment]
谢谢您这么久以来的授业解惑，非常感动。像您文章里描述的一样，而我的灵感来自于您。
送您一首我爱听的歌曲，希望喜欢。《keep your head up princess》

**Comment by shuizidesu** [comment]
> 问题解决了，您的想法真的太棒了！还有一个疑问，请问您的那些实验结果图是如何绘画的，以及意义是什么呢？看的不是很理解

中间层的结果全部输出出来保存好之后不管用和heatmap还是什么直接画就可以了。意义方面吧，其实很多时候这种中间结果图也很难得到理论上非常有意义的结果，不过可以稍微描述一下网络比较关注的区域，而且这种图也比较好看。

**Comment by Xiaohan-Chen** [comment]
很开心能帮到您，以及谢谢你分享的音乐^^
