### ISSUE TITLE
I want to get a PDF version of the paper

### ISSUE THREAD

**Issue by HAHADAYU** [XHChencs/baer_fault_diagnosis#4]
![image](https://github.com/Xiaohan-Chen/bear_fault_diagnosis/assets/114322119/49d1565f-0bd7-409e-96fc-3ecf3d5d6a25)

Hello, could you please send a PDF version of this article?

**Comment by Xiaohan-Chen** [comment]
Hi, thank you for your interest in our paper. Would you mind leaving your email so that I can send a copy of this paper to you?

**Comment by HAHADAYU** [comment]
> Hi, thank you for your interest in our paper. Would you mind leaving your email so that I can send a copy of this paper to you?您好，感谢您对我们论文的关注。您介意留下您的电子邮件，以便我可以将本文的副本发送给您吗？

Thank you very much. My email is 1290650103@qq.com。It's been a pleasure communicating with you.

**Comment by Xiaohan-Chen** [comment]
I have sent the pdf copy to your mail box, please check.

**Comment by HAHADAYU** [comment]
萍水相逢，不胜感激！
