### ISSUE TITLE
Require for the paper

### ISSUE THREAD

**Issue by KarenMars** [XHChencs/baer_fault_diagnosis#5]
Hi,

I'm an engineer who is also doing some experiments on bear fault diagnosis data. I would like to know whether I can have a pdf version of your paper "Bearing fault diagnosis base on multi-scale CNN and LSTM model". Looking forward to your reply, and thank you very much : )

Best regards,
KarenMars

**Comment by Xiaohan-Chen** [comment]
Hi Karen Mars,

Thank you for your interest in our paper. Would you mind leaving your email so I can send you a copy of our paper?

Best regards,
Xiaohan

**Comment by KarenMars** [comment]
Hi Xiaohan，

Thank you very much for the reply, it's a great help for us. My email address is **karen-in-winter@hotmail.com** . Have a nice day~

Best regards,
Karen Mars

**Comment by Xiaohan-Chen** [comment]
Dear Karen Mars,

I have sent the pdf copy to your mail box. Thanks again for your interest in our paper. Have a nice day!

Best regards,
Xiaohan
