### ISSUE TITLE
关于数据集的问题

### ISSUE THREAD

**Issue by qw13088049998** [XHChencs/baer_fault_diagnosis#8]
大佬您好，我想问一下我在西储大学官网下载的数据集单个故障最大长度是249146，您这个 np.array(file[key][0:480000]单个就取480000，请问是我下载的数据集不对吗？如果是的话，请问您的数据集是在哪里下的？

**Comment by Xiaohan-Chen** [comment]
论文中使用的是工况3下的数据，如果使用工况0或1的话有些故障数据是不足480000个的。

**Comment by qw13088049998** [comment]
感谢耐心解答 如沐春风 拨云见日 茅塞顿开

**Comment by Xiaohan-Chen** [comment]
不客气，祝科研顺利
